// przesyłam w tekstowym bo coś nie moge wysłać w makefile

drzewo.exe: main.o 
	gcc -Wall -o drzewo.exe  main.o 
drzewoBST.o: drzewoBST.c drzewoBST.h
	gcc -Wall -c drzewoBST.c 
main.o: main.c
	gcc -Wall -c main.c